### ISSUE TITLE
Like CRUD: Create a like

### ISSUE THREAD

**Issue by sbojorge** [sbojorge/Urban-drf#27]
EPIC #26 
As a **developer** I want to *add the like functionality** so that **users can show their interest in post that they like**.

## Acceptance criteria
  * Acceptance criteria 1: Only authenticated users can like posts.
  * Acceptance criteria 2: A user can't like twice the same post.
  * Acceptance criteria 3: The creation date is displayed.
 
## Tasks
 - [x] Task 1: Create the likes app and add it to INSTALLED APPS.
 - [x] Taks 2: Create the model and run the required migrations.
 - [x] Taks 3: Create the view, its url and add the likes urls to the main urls.py.
